service: aws-coldstart-nodejs6

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs6.10
  versionFunctions: false

functions:
  memory-128:
    handler: handler.hello
    memorySize: 128

  memory-256:
    handler: handler.hello
    memorySize: 256

  memory-512:
    handler: handler.hello
    memorySize: 512

  memory-1024:
    handler: handler.hello
    memorySize: 1024

  memory-1536:
    handler: handler.hello
    memorySize: 1536

  memory-3000:
    handler: handler.hello
    memorySize: 3000
